const employees=[
 {id:1,name:'Laura García',role:'Técnica',team:'Equipo A',status:'online',hours:'06:42',email:'empleado@puntotrabajo.demo'},
 {id:2,name:'Carlos Ruiz',role:'Operario',team:'Equipo A',status:'online',hours:'05:18'},
 {id:3,name:'Marta López',role:'Supervisora',team:'Equipo B',status:'pause',hours:'04:51'},
 {id:4,name:'David Martín',role:'Técnico',team:'Equipo B',status:'offline',hours:'00:00'},
 {id:5,name:'Ana Torres',role:'Operaria',team:'Equipo C',status:'online',hours:'07:03'}
];
const tasks=[
 ['Revisión de instalación','Laura García','Alta','En curso','Equipo A'],
 ['Entrega de material','Carlos Ruiz','Media','Pendiente','Equipo A'],
 ['Inspección zona norte','Marta López','Alta','Pendiente','Equipo B'],
 ['Parte de mantenimiento','Ana Torres','Baja','Completada','Equipo C']
];
const incidents=[
 ['Fuera de zona de trabajo','Carlos Ruiz','Hoy 10:14','Abierta','Equipo A'],
 ['Fichaje sin salida','David Martín','Ayer 18:07','En revisión','Equipo B'],
 ['Material dañado','Laura García','Ayer 15:32','Cerrada','Equipo A']
];

function session(){return Auth.getSession()}
function status(s){return `<span class="status ${s==='online'?'online':s==='pause'?'pause':'offline'}">${s==='online'?'Activo':s==='pause'?'En pausa':'Inactivo'}</span>`}
function teamEmployees(){const s=session();if(s.role==='admin')return employees;if(s.role==='supervisor')return employees.filter(e=>e.team===s.team);return employees.filter(e=>e.name===s.name)}
function teamTasks(){const s=session();if(s.role==='admin')return tasks;if(s.role==='supervisor')return tasks.filter(t=>t[4]===s.team);return tasks.filter(t=>t[1]===s.name)}
function teamIncidents(){const s=session();if(s.role==='admin')return incidents;if(s.role==='supervisor')return incidents.filter(i=>i[4]===s.team);return incidents.filter(i=>i[1]===s.name)}

function nav(active){
 const items=[['dashboard','Panel'],['employees','Empleados'],['users','Usuarios'],['map','Mapa en vivo'],['tasks','Tareas'],['hours','Horarios'],['incidents','Incidencias'],['reports','Informes'],['worker','Mi jornada']].filter(x=>Auth.can(x[0]));
 return `<aside><nav class="nav">${items.map(x=>`<button class="${active===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}<button class="nav-logout" onclick="Auth.logout()">Cerrar sesión</button></nav></aside>`
}
function shell(active,content){const s=session();if(!s)return renderLogin();document.querySelector('#app').innerHTML=`<div class="layout"><header class="top"><div class="brand">Punto <span>Trabajo</span></div><div class="user"><div class="user-meta"><b>${s.name}</b><small>${s.company} · ${s.roleLabel}</small></div><span class="avatar">${s.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span></div></header><div class="body">${nav(active)}<main>${content}</main></div></div>`}
function pageTitle(title,text,action=''){return `<div class="page-title"><div><h1>${title}</h1><p>${text}</p></div>${action}</div>`}

function dashboard(){if(!Auth.can('dashboard'))return go('worker');const es=teamEmployees(),ts=teamTasks(),is=teamIncidents();shell('dashboard',pageTitle('Panel de gestión',`${session().company} · Resumen del equipo · Hoy`,`<button class="btn primary" onclick="go('tasks')">+ Asignar tarea</button>`)+`<div class="grid metrics"><div class="card metric"><small>Empleados</small><strong>${session().role==='admin'?24:es.length}</strong><span class="muted">${session().role==='admin'?'12 equipos':session().team}</span></div><div class="card metric"><small>Activos ahora</small><strong>${es.filter(e=>e.status==='online').length}</strong><span class="muted">en tiempo real</span></div><div class="card metric"><small>Tareas de hoy</small><strong>${session().role==='admin'?31:ts.length}</strong><span class="muted">${ts.filter(t=>t[3]!=='Completada').length} pendientes</span></div><div class="card metric"><small>Geofencing</small><strong>${session().role==='admin'?2:is.filter(i=>i[0].toLowerCase().includes('zona')).length}</strong><span class="muted">alertas activas</span></div><div class="card metric"><small>Incidencias</small><strong>${session().role==='admin'?5:is.length}</strong><span class="muted">visibles</span></div></div><div class="grid two" style="margin-top:15px"><section class="card"><div class="section-head"><h2>Estado del equipo</h2><button class="btn secondary" onclick="go('employees')">Ver todos</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Empleado</th><th>Equipo</th><th>Estado</th><th>Jornada</th></tr></thead><tbody>${es.map(e=>`<tr><td><b>${e.name}</b><br><span class="muted">${e.role}</span></td><td>${e.team}</td><td>${status(e.status)}</td><td>${e.hours}</td></tr>`).join('')}</tbody></table></div></section><section class="card"><div class="section-head"><h2>Incidencias recientes</h2><button class="btn secondary" onclick="go('incidents')">Ver todas</button></div>${is.map(i=>`<div class="task"><b>${i[0]}</b><span class="muted">${i[1]} · ${i[2]}</span><div style="margin-top:7px"><span class="status ${i[3]==='Cerrada'?'online':i[3]==='En revisión'?'pause':'alert'}">${i[3]}</span></div></div>`).join('')||'<div class="empty">No hay incidencias.</div>'}</section></div><section class="card" style="margin-top:15px"><div class="section-head"><h2>Tareas de hoy</h2><button class="btn secondary" onclick="go('tasks')">Gestionar</button></div>${ts.map(t=>`<div class="task"><b>${t[0]}</b><span class="muted">${t[1]} · Prioridad ${t[2]}</span> <span class="status ${t[3]==='Completada'?'online':t[2]==='Alta'?'alert':'pause'}">${t[3]}</span></div>`).join('')}</section>`)}

function employeesPage(){const es=teamEmployees();shell('employees',pageTitle('Empleados',session().role==='supervisor'?'Personal de tu equipo.':'Gestiona la plantilla y sus equipos.',session().role==='admin'?'<button class="btn primary" onclick="addEmployee()">+ Añadir empleado</button>':'')+`<section class="card"><div class="filters"><input placeholder="Buscar empleado…" oninput="filterEmployees(this.value)"><select><option>Todos los equipos</option><option>Equipo A</option><option>Equipo B</option><option>Equipo C</option></select><select><option>Todos los estados</option><option>Activos</option><option>Inactivos</option></select></div><div class="table-wrap" style="margin-top:15px"><table class="table"><thead><tr><th>Empleado</th><th>Puesto</th><th>Equipo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody id="employeeRows">${employeeRows(es)}</tbody></table></div></section>`)}
function employeeRows(es){return es.map(e=>`<tr><td><b>${e.name}</b></td><td>${e.role}</td><td>${e.team}</td><td>${status(e.status)}</td><td><button class="btn secondary" onclick="toast('Ficha de ${e.name}')">Ver ficha</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No hay empleados.</td></tr>'}
function filterEmployees(q){const box=document.querySelector('#employeeRows');if(box)box.innerHTML=employeeRows(teamEmployees().filter(e=>e.name.toLowerCase().includes(q.toLowerCase())))}

function usersPage(){if(!Auth.can('users'))return forbidden();shell('users',pageTitle('Usuarios y permisos',`Control de acceso de ${session().company}.`,'<button class="btn primary" onclick="toast(\'Alta de usuario preparada\')">+ Añadir usuario</button>')+`<div class="grid two"><section class="card"><div class="section-head"><h2>Roles</h2></div><div class="role-card"><b>Administrador</b><span>Acceso completo a la empresa y a la gestión de usuarios.</span></div><div class="role-card"><b>Encargado</b><span>Acceso operativo limitado a su equipo asignado.</span></div><div class="role-card"><b>Empleado</b><span>Solo ve su jornada, tareas e información propia.</span></div></section><section class="card"><div class="section-head"><h2>Usuarios</h2><span class="status online">Activos</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Usuario</th><th>Rol</th><th>Equipo</th><th>Acción</th></tr></thead><tbody>${Auth.demoUsers.map(u=>`<tr><td><b>${u.name}</b><br><span class="muted">${u.email}</span></td><td>${u.roleLabel}</td><td>${u.team}</td><td><button class="btn secondary" onclick="toast('Gestión de usuario preparada')">Gestionar</button></td></tr>`).join('')}</tbody></table></div></section></div>`)}

async function mapPage(){const s=session();if(!s)return renderLogin();if(!(window.PuntoSupabase?.enabled&&s.provider==='supabase')){const es=teamEmployees().filter(e=>e.status!=='offline');shell('map',pageTitle('Mapa en vivo','La cuenta demo mantiene posiciones simuladas.','<button class="btn primary" onclick="toast(\'Actualizando posiciones…\')">Actualizar</button>')+`<div class="map-layout"><div class="card"><div id="map"></div></div><div class="card"><div class="section-head"><h2>Trabajadores</h2></div><div class="employee-list">${es.map(e=>`<div class="employee-item"><b>${e.name}</b><div>${status(e.status)} <span class="muted">· posición demo</span></div></div>`).join('')||'<div class="empty">No hay trabajadores visibles.</div>'}</div></div></div>`);return setTimeout(()=>initLiveMap([]),50)}shell('map',pageTitle('Mapa en vivo','Posiciones reales recibidas desde los dispositivos.','<button class="btn primary" onclick="mapPage()">Actualizar</button>')+'<div class="map-layout"><div class="card"><div id="map"></div></div><div class="card"><div class="section-head"><h2>Trabajadores</h2></div><div id="liveWorkers" class="employee-list"><div class="empty">Cargando posiciones…</div></div></div></div>');try{const client=PuntoSupabase.client;const m=await client.from('company_memberships').select('user_id').eq('company_id',s.companyId).eq('status','active');if(m.error)throw m.error;const ids=(m.data||[]).map(x=>x.user_id);let profiles=[];if(ids.length){const p=await client.from('profiles').select('id,full_name').in('id',ids);if(p.error)throw p.error;profiles=p.data||[]}const names=new Map(profiles.map(p=>[p.id,p.full_name||'Sin nombre']));const e=await client.from('location_events').select('user_id,latitude,longitude,accuracy_m,recorded_at,inside_geofence,geofence_id').eq('company_id',s.companyId).order('recorded_at',{ascending:false}).limit(500);if(e.error)throw e.error;const latest=new Map();(e.data||[]).forEach(x=>{if(!latest.has(x.user_id))latest.set(x.user_id,x)});const rows=ids.map(id=>({id,name:names.get(id)||'Sin nombre',event:latest.get(id)||null}));const box=document.querySelector('#liveWorkers');if(box)box.innerHTML=rows.map(r=>r.event?`<div class="employee-item" onclick="window.PuntoLiveMap?.focus('${r.id}')"><b>${escMap(r.name)}</b><div><span class="status online">Localizado</span> <span class="muted">· ${new Date(r.event.recorded_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})} · ±${Math.round(r.event.accuracy_m||0)} m</span></div></div>`:`<div class="employee-item"><b>${escMap(r.name)}</b><div><span class="status offline">Sin posición</span></div></div>`).join('')||'<div class="empty">No hay trabajadores.</div>';initLiveMap(rows)}catch(error){console.error(error);const box=document.querySelector('#liveWorkers');if(box)box.innerHTML='<div class="empty">'+escMap(error.message||'No se pudieron cargar las posiciones.')+'</div>'}}
function escMap(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initLiveMap(rows){if(typeof L==='undefined')return;const el=document.querySelector('#map');if(!el)return;const points=rows.filter(r=>r.event&&Number.isFinite(r.event.latitude)&&Number.isFinite(r.event.longitude)).map(r=>[r.event.latitude,r.event.longitude,r.name,r.id,r.event]);const center=points.length?[points[0][0],points[0][1]]:[36.51,-5.0];const map=L.map('map').setView(center,points.length?12:10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);const markers={};points.forEach(p=>{const m=L.marker([p[0],p[1]]).addTo(map).bindPopup('<b>'+escMap(p[2])+'</b><br>Última posición: '+new Date(p[4].recorded_at).toLocaleString('es-ES')+'<br>Precisión: ±'+Math.round(p[4].accuracy_m||0)+' m'+(p[4].inside_geofence===false?'<br><b>Fuera de geocerca</b>':''));markers[p[3]]=m});if(points.length>1)map.fitBounds(points.map(p=>[p[0],p[1]]),{padding:[30,30]});window.PuntoLiveMap={focus:id=>{if(markers[id]){map.setView(markers[id].getLatLng(),15);markers[id].openPopup()}}}}

function tasksPage(){const ts=teamTasks();const form=session().role==='employee'?'<div class="card"><h2>Mis tareas</h2><p class="muted">Solo puedes consultar y actualizar las tareas asignadas a tu cuenta.</p></div>':'<section class="card"><h2>Asignar tarea</h2><form class="form" onsubmit="event.preventDefault();toast(\'Tarea asignada correctamente\')"><label>Título<input required placeholder="Ej. Revisar instalación"></label><label>Empleado<select>'+teamEmployees().map(e=>`<option>${e.name}</option>`).join('')+'</select></label><div class="form-row"><label>Fecha<input type="date" value="2026-09-17"></label><label>Prioridad<select><option>Alta</option><option>Media</option><option>Baja</option></select></label></div><label>Descripción<textarea rows="4" placeholder="Detalles de la tarea"></textarea></label><button class="btn primary">Asignar tarea</button></form></section>';shell('tasks',pageTitle('Tareas','Asigna y controla el trabajo.',session().role==='employee'?'':'<button class="btn primary" onclick="createTask()">+ Asignar tarea</button>')+`<div class="grid two"><section class="card"><div class="section-head"><h2>Hoy</h2><select><option>Todos</option><option>Pendientes</option><option>En curso</option></select></div>${ts.map(t=>`<div class="task"><b>${t[0]}</b><span class="muted">${t[1]} · Prioridad ${t[2]}</span><div style="margin-top:8px"><span class="status ${t[3]==='Completada'?'online':t[2]==='Alta'?'alert':'pause'}">${t[3]}</span></div></div>`).join('')||'<div class="empty">No hay tareas.</div>'}</section>${form}</div>`)}
function hoursPage(){const es=teamEmployees();shell('hours',pageTitle('Horarios y fichajes','Consulta diaria, semanal o mensual y exporta informes.','<button class="btn primary" onclick="toast(\'Preparando PDF…\')">Exportar PDF</button>')+`<section class="card"><div class="filters"><select><option>Día</option><option>Semana</option><option>Mes</option></select><input type="date" value="2026-09-17"><select><option>Todos los empleados</option>${es.map(e=>`<option>${e.name}</option>`).join('')}</select></div><div class="table-wrap" style="margin-top:15px"><table class="table"><thead><tr><th>Empleado</th><th>Entrada</th><th>Salida</th><th>Duración</th><th>Flags</th><th>Acción</th></tr></thead><tbody>${es.map((e,i)=>`<tr><td><b>${e.name}</b></td><td>08:0${i}</td><td>${e.status==='offline'?'17:12':'—'}</td><td>${e.hours}</td><td>${i===1?'<span class="status alert">Fuera de zona</span>':'—'}</td><td><button class="btn secondary">Detalle</button></td></tr>`).join('')}</tbody></table></div></section>`)}
function incidentsPage(){const is=teamIncidents();shell('incidents',pageTitle('Incidencias','Abiertas, en revisión y cerradas.','<button class="btn primary" onclick="toast(\'Nueva incidencia\')">+ Nueva incidencia</button>')+`<section class="card"><div class="filters"><select><option>Todos los estados</option><option>Abiertas</option><option>En revisión</option><option>Cerradas</option></select><select><option>Todos los tipos</option><option>Geofencing</option><option>Fichaje</option><option>Operativa</option></select></div><div class="table-wrap" style="margin-top:15px"><table class="table"><thead><tr><th>Incidencia</th><th>Empleado</th><th>Fecha</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${is.map(i=>`<tr><td><b>${i[0]}</b></td><td>${i[1]}</td><td>${i[2]}</td><td><span class="status ${i[3]==='Cerrada'?'online':i[3]==='En revisión'?'pause':'alert'}">${i[3]}</span></td><td><button class="btn secondary">Abrir</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No hay incidencias.</td></tr>'}</tbody></table></div></section>`)}
function reportsPage(){shell('reports',pageTitle('Informes','Resumen de actividad según tu ámbito de acceso.','<button class="btn primary" onclick="toast(\'Generando informe PDF…\')">Exportar PDF</button>')+`<div class="grid metrics"><div class="card metric"><small>Horas del equipo</small><strong>164:32</strong><span class="muted">esta semana</span></div><div class="card metric"><small>Tareas completadas</small><strong>87%</strong><span class="muted">del total</span></div><div class="card metric"><small>Incidencias</small><strong>${teamIncidents().length}</strong><span class="muted">visibles</span></div><div class="card metric"><small>Alertas GPS</small><strong>7</strong><span class="muted">este mes</span></div><div class="card metric"><small>Fichajes</small><strong>428</strong><span class="muted">este mes</span></div></div><section class="card" style="margin-top:15px"><div class="section-head"><h2>Resumen por empleado</h2><select><option>Este mes</option><option>Esta semana</option><option>Hoy</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>Empleado</th><th>Horas</th><th>Tareas</th><th>Completadas</th><th>Incidencias</th><th>Geofencing</th></tr></thead><tbody>${teamEmployees().map((e,i)=>`<tr><td><b>${e.name}</b></td><td>${30+i*2}:2${i}</td><td>${8+i}</td><td>${7+i}</td><td>${i%2}</td><td>${i===1?2:0}</td></tr>`).join('')}</tbody></table></div></section>`)}
function workerPage(){const s=session();shell('worker',`<div class="employee-mobile">${pageTitle('Mi jornada',`Hola, ${s.name.split(' ')[0]}. Aquí tienes tu jornada de hoy.`)}<section class="card"><span class="status online">En jornada</span><div class="clock">06:42</div><p class="muted">Tiempo trabajado hoy</p><div class="mobile-actions"><button class="btn danger big" onclick="toast('Salida registrada')">Fichar salida</button><button class="btn secondary big" onclick="toast('Pausa iniciada')">Iniciar pausa</button></div></section><section class="card" style="margin-top:15px"><div class="section-head"><h2>Mis tareas de hoy</h2></div>${teamTasks().map(t=>`<div class="task"><b>${t[0]}</b><span class="muted">${t[2]} · ${t[3]}</span></div>`).join('')||'<div class="empty">No tienes tareas asignadas.</div>'}</section><section class="card" style="margin-top:15px"><div class="section-head"><h2>Mi ubicación</h2></div><p>La ubicación se registra según las reglas de fichaje y geofencing de la empresa.</p><button class="btn secondary" onclick="toast('Ubicación comprobada')">Comprobar ubicación</button></section></div>`)}
function forbidden(){shell('',`<section class="card"><h1>Acceso no autorizado</h1><p class="muted">Tu rol no dispone de permisos para esta sección.</p><button class="btn primary" onclick="go(session().role==='employee'?'worker':'dashboard')">Volver</button></section>`)}
function addEmployee(){toast('Alta de empleado preparada para conectar con el backend')}
function createTask(){document.querySelector('.form input')?.focus();toast('Usa el formulario para crear una tarea')}
function toast(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function go(page){const routes={dashboard,tasks:tasksPage,employees:employeesPage,users:usersPage,map:mapPage,hours:hoursPage,incidents:incidentsPage,reports:reportsPage,worker:workerPage};if(!session())return renderLogin();if(!Auth.can(page))return go(session().role==='employee'?'worker':'dashboard');(routes[page]||dashboard)()}
if(session())go(session().role==='employee'?'worker':'dashboard');else renderLogin();
