(function(){
  const demoPositions=[
    {user_id:'demo-laura',name:'Laura García',latitude:36.510,longitude:-4.885,recorded_at:new Date().toISOString(),inside_geofence:true},
    {user_id:'demo-carlos',name:'Carlos Ruiz',latitude:36.520,longitude:-4.870,recorded_at:new Date().toISOString(),inside_geofence:true},
    {user_id:'demo-marta',name:'Marta López',latitude:36.500,longitude:-4.900,recorded_at:new Date().toISOString(),inside_geofence:false},
    {user_id:'demo-ana',name:'Ana Torres',latitude:36.530,longitude:-4.890,recorded_at:new Date().toISOString(),inside_geofence:true}
  ];
  let map=null, markerLayer=null, fenceLayer=null, refreshTimer=null;
  function age(iso){if(!iso)return 'sin datos';const mins=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/60000));if(mins<1)return 'ahora';if(mins===1)return 'hace 1 min';return `hace ${mins} min`;}
  function labelPosition(p){return p.profiles?.full_name||p.name||'Empleado';}
  function cleanText(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
  function markerIcon(inside){return L.divIcon({className:'pt-live-marker',html:`<span class="pt-live-dot ${inside?'inside':'outside'}"></span>`,iconSize:[22,22],iconAnchor:[11,11]});}
  function demoFallbackPositions(){const current=teamEmployees().map(e=>e.name);return demoPositions.filter(p=>current.includes(p.name));}
  function setupMap(){const el=document.querySelector('#map');if(!el||typeof L==='undefined')return false;if(map){map.remove();map=null;}map=L.map(el).setView([36.51,-4.885],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);markerLayer=L.layerGroup().addTo(map);fenceLayer=L.layerGroup().addTo(map);return true;}
  function drawMap(locations,zones){if(!map)return;markerLayer.clearLayers();fenceLayer.clearLayers();for(const z of zones)L.circle([z.latitude,z.longitude],{radius:Number(z.radius_m),weight:2,fillOpacity:.12}).addTo(fenceLayer).bindPopup(`<b>${cleanText(z.name)}</b><br>Radio: ${Number(z.radius_m).toLocaleString('es-ES')} m`);const bounds=[];for(const p of locations){const lat=Number(p.latitude),lon=Number(p.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;bounds.push([lat,lon]);const inside=p.inside_geofence!==false;L.marker([lat,lon],{icon:markerIcon(inside)}).addTo(markerLayer).bindPopup(`<b>${cleanText(labelPosition(p))}</b><br><span>${inside?'Dentro de zona':'Fuera de zona'}</span><br><span>${age(p.recorded_at)}</span>${p.accuracy_m?`<br>Precisión: ±${Math.round(p.accuracy_m)} m`:''}`);}if(bounds.length)map.fitBounds(bounds,{padding:[35,35],maxZoom:14});else if(zones.length)map.fitBounds(zones.map(z=>[z.latitude,z.longitude]),{padding:[35,35],maxZoom:13});}
  function renderWorkers(locations,zones,canManage){const box=document.querySelector('#liveWorkers');if(!box)return;box.innerHTML=locations.map(p=>{const inside=p.inside_geofence!==false;return `<div class="employee-item"><b>${cleanText(labelPosition(p))}</b><div><span class="status ${inside?'online':'alert'}">${inside?'Dentro de zona':'Fuera de zona'}</span> <span class="muted">· ${age(p.recorded_at)}</span></div>${p.accuracy_m?`<small class="muted">Precisión ±${Math.round(p.accuracy_m)} m</small>`:''}</div>`;}).join('')||'<div class="empty">No hay ubicaciones recientes.</div>';const zoneBox=document.querySelector('#geofenceList');if(zoneBox)zoneBox.innerHTML=zones.map(z=>`<div class="geofence-row"><div><b>${cleanText(z.name)}</b><small>${Math.round(Number(z.radius_m)).toLocaleString('es-ES')} m · ${Number(z.latitude).toFixed(5)}, ${Number(z.longitude).toFixed(5)}</small></div>${canManage?`<button class="btn danger" onclick="deleteGeofence('${z.id}')">Eliminar</button>`:''}</div>`).join('')||'<div class="empty">No hay geocercas configuradas.</div>';}
  async function refresh(){try{const [zones,live]=await Promise.all([PuntoGeo.getZones(),PuntoGeo.latestLocations()]);const s=session(),canManage=s.role==='admin';let locations=live;if(!(s.provider==='supabase'&&PuntoSupabase?.enabled)&&!locations.length)locations=demoFallbackPositions();drawMap(locations,zones);renderWorkers(locations,zones,canManage);const summary=document.querySelector('#mapLiveSummary');if(summary)summary.textContent=`${locations.length} ubicaciones · ${zones.length} geocercas · actualización ${new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`;}catch(err){console.error('Punto Trabajo mapa:',err);const summary=document.querySelector('#mapLiveSummary');if(summary)summary.textContent='No se han podido actualizar las posiciones.';toast(err?.message||'No se pudo actualizar el mapa.');}}
  async function useMyLocationForFence(){try{const p=await PuntoGeo.position();document.querySelector('#fenceLat').value=p.latitude.toFixed(6);document.querySelector('#fenceLng').value=p.longitude.toFixed(6);toast('Coordenadas actuales cargadas.');}catch(err){toast(err?.message||'No se pudo obtener la ubicación.');}}
  async function addGeofence(event){event.preventDefault();try{await PuntoGeo.createZone({name:document.querySelector('#fenceName').value,latitude:document.querySelector('#fenceLat').value,longitude:document.querySelector('#fenceLng').value,radius_m:document.querySelector('#fenceRadius').value});event.target.reset();document.querySelector('#fenceRadius').value=500;toast('Geocerca creada.');await refresh();}catch(err){toast(err?.message||'No se pudo crear la geocerca.');}}
  async function deleteGeofence(id){if(!confirm('¿Eliminar esta geocerca?'))return;try{await PuntoGeo.removeZone(id);toast('Geocerca eliminada.');await refresh();}catch(err){toast(err?.message||'No se pudo eliminar la geocerca.');}}
  window.useMyLocationForFence=useMyLocationForFence;window.addGeofence=addGeofence;window.deleteGeofence=deleteGeofence;
  window.mapPage=function(){const s=session(),canManage=s.role==='admin';if(!Auth.can('map'))return go(s.role==='employee'?'worker':'dashboard');shell('map',pageTitle('Mapa en vivo','Posición, fichajes y geocercas según tus permisos.',`<div class="map-actions"><button class="btn secondary" onclick="refreshLiveMap()">Actualizar</button>${canManage?'<button class="btn primary" onclick="document.querySelector(\'#newGeofence\')?.scrollIntoView({behavior:\'smooth\'})">+ Geocerca</button>':''}</div>`)+`<div class="map-live-meta" id="mapLiveSummary">Cargando posiciones…</div><div class="map-layout live-map-layout"><div class="card"><div id="map"></div></div><div class="card"><div class="section-head"><h2>Trabajadores</h2><span class="muted">Últimos 30 min</span></div><div class="employee-list" id="liveWorkers"></div></div></div>${canManage?`<div class="grid two" style="margin-top:15px"><section class="card" id="newGeofence"><div class="section-head"><div><h2>Nueva geocerca</h2><p class="muted">Define una zona en la que se controla la presencia del equipo.</p></div></div><form class="form" onsubmit="addGeofence(event)"><label>Nombre<input id="fenceName" required placeholder="Ej. Obra Marbella Centro"></label><div class="form-row"><label>Latitud<input id="fenceLat" type="number" step="any" required placeholder="36.51"></label><label>Longitud<input id="fenceLng" type="number" step="any" required placeholder="-4.88"></label></div><div class="form-row"><label>Radio (metros)<input id="fenceRadius" type="number" min="10" max="100000" value="500" required></label><div class="fence-location-action"><button type="button" class="btn secondary" onclick="useMyLocationForFence()">Usar mi ubicación</button></div></div><button class="btn primary">Crear geocerca</button></form></section><section class="card"><div class="section-head"><h2>Geocercas activas</h2><span class="status online">Controladas</span></div><div id="geofenceList" class="geofence-list"></div></section></div>`:''}`);setupMap();refresh();clearInterval(refreshTimer);refreshTimer=setInterval(refresh,15000);};
  window.refreshLiveMap=refresh;window.addEventListener('beforeunload',()=>clearInterval(refreshTimer));
})();
